### ISSUE TITLE
Question: Directory location and structure for unit-level XSpec tests

### ISSUE THREAD

**Issue by galtm** [usnistgov/metaschema-xslt#63]
I'm starting to work on unit-level XSpec tests in this repo. I happen to be starting with the XML-to-JSON converter generator code. By unit-level, I mean tests that target specific XSLT functions and XSLT templates; my tests will complement (not replace) tests that operate at higher levels, such as end-to-end.

@wendellpiez , @aj-stein-nist , @nikitawootten-nist : I am looking for input or recommendations on where to put the tests and any data files they require as sources or expected outputs.

### Idea 1: Near higher-level tests
This repo already has a directory `src/testing`. Unit-level tests could be in a directory like
```
src/testing/converter-gen/xml-to-json
```
or possibly one level deeper, to allow growth of non-unit-level tests.
```
src/testing/unit/converter-gen/xml-to-json
```

### Idea 2: Near the code units being tested
This repo already has a directory `src/compose/testing` . Unit-level tests for the XML-to-JSON converter generator code could be in an analogous directory like
```
src/converter-gen/testing/xml-to-json
```

### Other ideas?
I'm open to other ideas or variations on these ideas.

**Comment by nikitawootten-nist** [comment]
My personal view is that we should keep tests close to the functionality being tested. The `src/testing` directory is a convenient place to put common testing artifacts (and maybe end-to-end tests in the future that exercise conversion and schema generation, etc).

**Comment by wendellpiez** [comment]
That's a vote for option 2.

Here's a refinement:
- `src/testing` includes resources for global-level testing, not to be moved or edited without fully testing all test runtimes
- `src/**/testing` include (functional) testing for utilities in a given folder
- `examples` (tbd) includes top-level independent metaschema examples useful for testing

I am thinking of `examples` because I already have one or two Metaschema-based examples in mind that would be useful and interesting to develop, but *outside* the dependency chain of the application unit testing. Calling it `examples` would help distinguish it from tests that are used to test Metaschema, as opposed to testing ideas using Metaschema.

@galtm is this amenable? If so, should we say so in the `TESTING` file...

**Comment by galtm** [comment]
Thanks for the input, @nikitawootten-nist and @wendellpiez . Yes, it sounds good to me. What is the `TESTING` file, though?

I used this directory structure with pull request #64, so I think I don't need to change that.  : )

**Comment by nikitawootten-nist** [comment]
> Yes, it sounds good to me. What is the `TESTING` file, though?

@galtm we've interpreted NIST requirements for public repositories to contain some sort of documented "testing plan" (see https://github.com/usnistgov/metaschema-xslt/issues/4).

*When* we're comfortable with calling the repository "stable", publishing it, and giving it a DOI, we'll work towards writing a testing document similar to [`TESTING.md` in OSCAL-deep-diff](https://github.com/usnistgov/oscal-deep-diff/blob/master/TESTING.md).

**Comment by wendellpiez** [comment]
It is a good question. There is a file https://github.com/wendellpiez/metaschema-xslt/blob/issue53-smoketesting/src/schema-gen/TESTING.md in the working branch being staged, but as of yet no other TESTING or rules about TESTING in this repo (on its way as @nikitawootten-nist describes).

Those too have to be refined a little - sorry for getting a little ahead of myself. 🐰

**Comment by galtm** [comment]
Thanks for the information. A documented testing policy sounds great!

BTW, @nikitawootten-nist , your deep diff tool is awesome. I saw one of your presentations about it.

**Comment by wendellpiez** [comment]
FF to let me know if this wants revisiting.
